//function declarations
void initializePinModes(int[], char[]);
void wait(int);
void AnWriteLights(int[], int);
void count_down(int, int);
void SingleFlash(int[]);
void DoubleFlash(int, int, int);
void DoubleFlashFinal(int, int);
void FlashBuild(int, int);
void bulletshot(int[4], int[16]);
void DoubleSpeedFlash(int, int);
void preBullets(int[4]);
void chorus(int, int, int);
void intimidate(int[4], int, int, int, int, int, int);
void intimidate_rev(int[4], int, int, int, int, int, int);
void intimidate_half(int[4], int, int, int, int, int, int);
void intimidate_half_sd(int, int);
void intimidate_half_sdb(int[4], int, int);
void INTIMIDATE_FINAL(int bulletsPower[4], int, int, int, int, int, int);
static void Play_Music( void );
static void Stop_Music( void );
